name: build

on:
  push:
    branches:
      - 'master'
  schedule:
    # everyday 11AM (UTC)
    - cron: '* 9 * * *'
  workflow_dispatch:
    branches:
      - 'master'
  workflow_run:
    workflows:
      - 'sync-upstream'
    branches:
      - 'master'
    types:
      - completed

jobs:
  build-tmx:
    name: Build tmx
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache bundle directory
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      - name: Configure git
        run: |
          bin/configure-git
      - name: Setup build env
        run: |
          bin/setup-build-env
      - name: Update tmx
        run: bin/update-tmx

      - name: Push changes
        run: bin/push-changes "Update tmx"

  deploy-ja:
    name: Deploy Japanese translation to GitHub pages
    # Deploy a localized site to the GitHub pages
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # Checkout target revision from git repository
        uses: actions/checkout@v2
      - name: Cache bundle directory
        # Cache ruby bundle directory to speed up build
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
      - name: Setup build env
        # Setup build environment(install runtime, library, etc.)
        run: |
          bin/setup-build-env
      - name: Configure git
        # Setup git configuration
        run: |
          bin/configure-git

      - name: Exec po4a-translate
        # Execute po4a-translate to translate files based on .po files
        run: bin/exec-po4a-translate

      - name: Apply override files
        # Some files cannot be translated by po4a utility.
        # In that case, the files are copied to `l10n/override/<locale>/` directory and translated manually
        # This step copies the stored translated files to corresponding location.
        run: bin/exec-override

      - name: Exec jekyll
        # Execute jekyll to build a localized site
        run: bin/exec-jekyll

      - name: Deploy to GitHub Pages
        # Deploy the site to GitHub Pages by committing and pushing the site
        run: |
          #echo "ja.infinispan.org" > docs/CNAME #TODO: uncomment
          git add -f docs

          set +e
          git diff --cached --exit-code --quiet

          if [[ $? -eq 1 ]] ; then
            set -e
            git checkout -b docs
            git commit -m "Update GitHub Pages"
            git fetch
            git push -f origin docs
          fi
          set -e
